<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="course" nsURI="platform:/plugin/assignment1/model/course.ecore"
    nsPrefix="course">
  <eClassifiers xsi:type="ecore:EClass" name="University">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="faculties" upperBound="-1"
        eType="#//Faculty" containment="true" eOpposite="#//Faculty/university"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="people" lowerBound="1"
        upperBound="-1" eType="#//Person" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Faculty">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="university" eType="#//University"
        eOpposite="#//University/faculties"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="departments" upperBound="-1"
        eType="#//Department" containment="true" eOpposite="#//Department/faculty"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="shortName" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Course">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="code" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="content" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="credits" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="studyPrograms" upperBound="-1"
        eType="#//StudyProgram"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="courseInstances" upperBound="-1"
        eType="#//CourseInstance" containment="true" eOpposite="#//CourseInstance/course"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="department" lowerBound="1"
        eType="#//Department" eOpposite="#//Department/courses"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="preRequisities" upperBound="-1"
        eType="#//Course"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dependentCourses" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EEList" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CourseInstance">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="scheduledHours"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="course" lowerBound="1"
        eType="#//Course" eOpposite="#//Course/courseInstances"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="organisation" lowerBound="1"
        eType="#//Organisation" containment="true" eOpposite="#//Organisation/courseInstance"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="evaluation" lowerBound="1"
        eType="#//Evaluation" containment="true" eOpposite="#//Evaluation/courseInstance"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="courseWork" lowerBound="1"
        eType="#//CourseWork" containment="true" eOpposite="#//CourseWork/courseInstance"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="timeTable" lowerBound="1"
        eType="#//Timetable" containment="true" eOpposite="#//Timetable/courseInstance"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="semester" lowerBound="1"
        eType="#//semesterType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Department">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="shortName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="courses" upperBound="-1"
        eType="#//Course" containment="true" eOpposite="#//Course/department"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="studyPrograms" lowerBound="1"
        upperBound="-1" eType="#//StudyProgram" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="faculty" lowerBound="1"
        eType="#//Faculty" eOpposite="#//Faculty/departments"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Person">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="employment" lowerBound="1"
        upperBound="-1" eType="#//Employment" eOpposite="#//Employment/employee"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="studies" eType="#//Studies"
        containment="true" eOpposite="#//Studies/student"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Evaluation">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="exam" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="project" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="assigments" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="courseInstance" eType="#//CourseInstance"
        eOpposite="#//CourseInstance/evaluation"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Organisation">
    <eStructuralFeatures xsi:type="ecore:EReference" name="courseInstance" eType="#//CourseInstance"
        eOpposite="#//CourseInstance/organisation"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="employees" upperBound="-1"
        eType="#//Employment" containment="true" eOpposite="#//Employment/organisation"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="StudyProgram">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="code" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CourseWork">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="lectureHours" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="labHours" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="courseInstance" lowerBound="1"
        eType="#//CourseInstance" eOpposite="#//CourseInstance/courseWork"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Timetable">
    <eStructuralFeatures xsi:type="ecore:EReference" name="courseInstance" lowerBound="1"
        eType="#//CourseInstance" eOpposite="#//CourseInstance/timeTable"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="timetableEntry" lowerBound="1"
        upperBound="-1" eType="#//TimetableEntry" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TimetableEntry">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="day" lowerBound="1" eType="#//DayOfWeek"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="room" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="time" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="studyProgram" upperBound="-1"
        eType="#//StudyProgram"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="#//TypeOfInstruction"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="DayOfWeek">
    <eLiterals name="Monday" value="1"/>
    <eLiterals name="Tuesday" value="2" literal="Tuesday"/>
    <eLiterals name="Wednesday" value="3" literal="Wednesday"/>
    <eLiterals name="Thursday" value="4" literal="Thursday"/>
    <eLiterals name="Friday" value="5"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="TypeOfInstruction">
    <eLiterals name="Lab" value="1" literal="Lab"/>
    <eLiterals name="Lecture" value="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="TypeOfEmployment">
    <eLiterals name="Student" value="1" literal="Student"/>
    <eLiterals name="TA" value="2"/>
    <eLiterals name="Lecturer" value="3"/>
    <eLiterals name="CourseCoordinator" value="4"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Employment">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="cannotBeStudentAndTAInSameCourse"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="employment" lowerBound="1"
        upperBound="-1" eType="#//TypeOfEmployment"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="employee" lowerBound="1"
        eType="#//Person" eOpposite="#//Person/employment"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="organisation" lowerBound="1"
        eType="#//Organisation" eOpposite="#//Organisation/employees"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Studies">
    <eStructuralFeatures xsi:type="ecore:EReference" name="pastCourses" upperBound="-1"
        eType="#//Course"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="student" lowerBound="1"
        eType="#//Person" eOpposite="#//Person/studies"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="currentCourses" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EEList" volatile="true"
        transient="true" derived="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="semesterType">
    <eLiterals name="Spring"/>
    <eLiterals name="Fall" value="1"/>
  </eClassifiers>
</ecore:EPackage>
